version: '3'

services:
    fio-sameapp:
        build:
            context: .
            dockerfile: ../dockerFiles/fio/Dockerfile 
        volumes:
            - /mnt/resource:/mnt/resource
            - /mnt/${DEV}:/mnt/${DEV}
        command: "--name test --direct=1 --ioengine=libaio --iodepth=${QD} \
                  --filename=/mnt/${DEV}/${FILE} --rw=${PATTERN} \
                  --bs=${BS} --time_based --runtime=15 --ramp_time=0 --log_avg_msec=${LOG_MSEC} \
                  --write_lat_log=${TS_LOG_FILE}\
                  --write_bw_log=${TS_LOG_FILE} \
                  --write_iops_log=${TS_LOG_FILE} \
                  --output=${FIO_LOG_FILE}"
