version: '3'

services:
    fio-single:
        build:
            context: .
            dockerfile: ../dockerFiles/fio/Dockerfile 
        volumes:
            - /mnt/resource:/mnt/resource
            - /mnt/nvme1n1:/mnt/nvme1n1
        command: "--name test --direct=1 --ioengine=libaio --iodepth=32 --filename=/mnt/nvme1n1/text1 --rw=read \
                  --bs=4k --time_based --runtime=5"

    fio-multi:
        build:
            context: .
            dockerfile: ../dockerFiles/fio/Dockerfile
        volumes:
            - /mnt/resource:/mnt/resource
            - /mnt/nvme1n2:/mnt/nvme1n2
        command: "--name test --direct=1 --ioengine=libaio --iodepth=32 --filename=/mnt/nvme1n2/text1 --rw=read \
                  --bs=4k --time_based --runtime=5"
